### ISSUE TITLE
Add kubelet resource metric scraping to performance dashboards

### ISSUE THREAD

**Issue by ehashman** [kubernetes/perf-tests#1789] opened 2021-04-27 22:37 UTC
**What would you like to be added**:

Per https://kubernetes.slack.com/archives/C09QZTRH7/p1619422034034900?thread_ts=1619223170.034800&cid=C09QZTRH7 kubelet resource scraping currently is not supported by clusterloader2. I would like kubelet resource utilization to be tracked in the performance tests and dashboards.

**Why is this needed**:

Without this support, if there is e.g. a CPU or memory utilization regression, we don't have an easy way to detect it with the performance dashboards like http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-1.20&metriccategoryname=E2E&metricname=LoadResources&PodName=kube-apiserver-e2e-big-master%2Fkube-apiserver&Resource=CPU for API server.

**Comment by SergeyKanzhelev** [comment] 2021-04-28 17:17
This exists: http://node-perf-dash.k8s.io/#/builds Maybe need to be revived?

@wojtek-t can you please suggest what's the best way to track kubelet related perf?

**Comment by wojtek-t** [comment] 2021-04-29 13:38
I think those are two slightly separate things:

1) I agree that kubelet resource-usage would be useful and adding that support for clusterloade2 makes sense
[it's just a new feature, because so far we're gathering the data from metrics-server/kubelet, which doesn't expose data about kubelet]. @ehashman - what would be the best source of getting this kind of data?

@marseel @mborsz - can you please follow up with Elana on this?

2) node-perf-dash absolutely makes sense, but it was never owned by SIG-scalability - it was set up and owned by SIG-node for SIG-owned node tests.

**Comment by ehashman** [comment] 2021-04-29 20:18
I think we should probably deprecate node-perf-dash and fold as much of it into perf-dash as possible. I'm not sure who previously maintained it.

@wojtek-t do we run [node_exporter](https://github.com/prometheus/node_exporter) on our test clusters? That's one option for getting system CPU utilization. We use this in OpenShift to set up a recording rule in Prometheus to aggregate CPU utilization across the entire cluster.

`container_cpu_user_seconds_total{id=~"/system.slice/.*"}` is the other way OpenShift is measuring this. We could also hit the `/debug/pprof/profile` endpoints on the kubelets during CI runs to grab profiles for each run.

**Comment by wojtek-t** [comment] 2021-04-30 05:55
> @wojtek-t do we run node_exporter on our test clusters? That's one option for getting system CPU utilization. We use this in OpenShift to set up a recording rule in Prometheus to aggregate CPU utilization across the entire cluster.

We have an option to run it - I can't remember if this is enabled or not.
@marseel or @mborsz will follow up on it.

**Comment by mborsz** [comment] 2021-04-30 07:16
@ehashman We do have node exporter running on master.

https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/exporters/node_exporter/node-exporter.yaml

It is being deployed using a hack: https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/prometheus.go#L305

I can't remember exactly why we decided to ssh to the master and copy static pod there instead of creating daemonset. Based on the comment "Consider migrating to something less ugly, e.g. daemonset-based approach, when master nodes have configured networking." most likely it was caused by the fact that masters in kubermark have no network configured properly, but I think it's OK to simply ignore kubermark -- we never used this there.

So I think the steps here are:
* Migrate "runNodeExporter" to use daemonset with node selector instead of a static pod
* Assign the node selector to the master and (potentially subset of) nodes.
* Prometheus will start gathering metrics from node exporter
* We prepare a measurement that will translate prometheus query' result to perf-dash metric (similar to https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/measurement/common/scheduling_throughput_prometheus.go)
* Win!

The main concern here is a scalability of prometheus itself: 5k objects to scrape may generate significant load on prometheus. We can solve this issue by either:
* Fetch from all nodes, but significantly reducing scraping interval (like e.g. 10m in https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/default/prometheus-podMonitorNodeLocalDNS.yaml#L12)
* Fetch data with higher granularity, but only from a subset of nodes (I guess the nodes should have similar cpu/network/memory pattterns, so a random subset should give representative result).

Personally I would try to gather all of them, but with reduced granularity (as it may be simpler), with the second option as a fallback if this doesn't work.

There is also one potential approach here: instead of gathering node-exporter, we can try to gather kubelet. In fact prometheus-operator already implements an option to fetch data from all kubelets (https://github.com/prometheus-operator/prometheus-operator/blob/7f94a06b86d41c20176f0d5b53aa0100fdc361e6/pkg/prometheus/operator.go#L575-L576), but it's not clear to me if it's going to work in 5k scale:
* It periodically lists all nodes in the system
* Translates result into a single endpoint object (which is going to be huge)
* The created endpoint object doesn't have any headless label, which will populate this endpoint to all kube-dns instances
* (I'm not sure if this is true) endpointslicemirroring will mirror this endpoint object into endpointslices object and they will go to all kube-proxies generating even more load.

For all those reasons, I think we should either improve prometheos-operator' kubelet gathering or implement node-exporter-based one.

**Comment by aojea** [comment] 2021-05-26 22:22
/assign
I was checking this today, we didn't detect a big regression that caused test to flake during a month

**Comment by SergeyKanzhelev** [comment] 2021-06-15 17:41
@aojea where are those metrics now visible? Do you have a quick link?

**Comment by aojea** [comment] 2021-06-15 18:21
> @aojea where are those metrics now visible? Do you have a quick link?

http://perf-dash.k8s.io/#/?jobname=gce-100Nodes-master&metriccategoryname=E2E&metricname=LoadResources&PodName=e2e-big-minion-group%2Fkubelet&Resource=CPU

**Comment by ehashman** [comment] 2021-06-30 17:37
Looks like this is available now on master and 1.21 but not <=1.20.

This is awesome!!! :tada:

**Comment by SergeyKanzhelev** [comment] 2021-07-16 00:22
/reopen

@aojea what will it take to enable it for 1.20? Right now kubelet metrics only available on `1.21` and `master`

**Comment by aojea** [comment] 2021-07-16 00:52
> /reopen
> 
> @aojea what will it take to enable it for 1.20? Right now kubelet metrics only available on `1.21` and `master`

@SergeyKanzhelev sorry, I missed this message, I don't know exactly how the scale jobs work and how to backport it, better ask @wojtek-t and scalability folks

**Comment by wojtek-t** [comment] 2021-07-16 06:34
> @SergeyKanzhelev sorry, I missed this message, I don't know exactly how the scale jobs work and how to backport it, better ask @wojtek-t and scalability folks

perf-tests repo is branched the same way as k/k - we should just cherrypick it back to previous branches.

[Actually - it should only work for `master` (or are you asking about our internal GKE tests where we version a bit differently?]

**Comment by aojea** [comment] 2021-07-16 09:57
/close
cherrypick has merged
@SergeyKanzhelev feel free to reopen if there is something missing

**Closed by aojea** 2021-07-16 09:57 UTC
Labels: kind/feature
